name: $(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: self
      type: git
      name: RaceTrac Portfolio/mobile-taf
      ref: master
      trigger:
        - master

pool:
  name: default

stages:
  - stage: Test Android compiliance
    jobs:
      - job: Compile
        steps:
          - script: mvn clean compile -Dtest.config=android
  
  
  - stage: Test IOS compiliance
    jobs:
      - job: Test
        steps:
          - script: mvn clean compile -Dtest.config=ios
              