properties:
  #Config

  android_appium_hub: &android_appium_hub
    hub: http://127.0.0.1:4723/wd/hub

  ios_appium_hub: &ios_appium_hub
    hub: http://127.0.0.1:4724/wd/hub

  #Android section
  platformAndroid: &AndroidPlatform
    platformName: Android
    appPackage: com.RaceTrac.Common.qa
    deviceName: Emulator
    test.profile: android
    autPackage: src/main/resources/apk
    appActivity: com.RaceTrac.ui.splash.SplashScreenActivity
    udid: emulator-5554

  #iOS section
  platformIos: &iOsPlatform
    platformName: ios
    platformVersion: 14.5
    deviceName: iPhone 11
    test.profile: ios
    bundleId: com.racetrac.QA.ams
    autPackage: src/main/resources/apk

  iosConfig: &iosConfig
    <<: *iOsPlatform
    <<: *ios_appium_hub #port 4724

  AndroidConfig: &AndroidConfig
    <<: *AndroidPlatform
    <<: *android_appium_hub #port 4723

  #test.config
  ios:
    <<: *iosConfig

  android:
    <<: *AndroidConfig

